# Generated by Django 4.2.4 on 2023-08-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="data",
            field=models.CharField(max_length=2000),
        ),
    ]
