# Generated by Django 4.2.4 on 2023-08-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0002_alter_page_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="content",
            field=models.JSONField(default=dict),
        ),
    ]
