# Generated by Django 4.2.4 on 2023-08-06 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0004_remove_page_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
